export const SKY_WONDERLAND_MODES = [
  {
    id: "constellation",
    label: "Sterne",
    icon: "Star",
    target: 5,
  },
  {
    id: "clouds",
    label: "Wolken",
    icon: "Cloud",
    target: 4,
  },
  {
    id: "moon",
    label: "Mond",
    icon: "Moon",
    target: 3,
  },
  {
    id: "comets",
    label: "Kometen",
    icon: "Sparkles",
    target: 6,
  },
  {
    id: "rainbow",
    label: "Regenbogen",
    icon: "Sparkles",
    target: 6,
  },
  {
    id: "treasure",
    label: "Schatz",
    icon: "Star",
    target: 4,
  },
];

export const SKY_SKYLINE_ASSETS = [
  "/premium-sky/backgrounds/sky-aurora.jpg",
  "/premium-sky/backgrounds/sky-rainbow.jpg",
  "/premium-sky/backgrounds/sky-night.jpg",
  "/premium-sky/backgrounds/sky-morning.jpg",
  "/premium-sky/backgrounds/sky-rain.jpg",
  "/premium-sky/backgrounds/sky-sunset.jpg",
  "/sky-bitmaps/sky-world.webp",
  "/sky-bitmaps/rainbow-arc.webp",
  "/sky-bitmaps/treasure-instruments.webp",
];

export const SKY_SPRITES = {
  sun: "/premium-sky/sprites/sun-medallion.png",
  cloudA: "/premium-sky/sprites/cloud-soft-1.png",
  cloudB: "/premium-sky/sprites/cloud-soft-2.png",
  cloudPeach: "/premium-sky/sprites/cloud-peach.png",
  rainbow: "/premium-sky/sprites/rainbow-arc.png",
  moon: "/premium-sky/sprites/moon-crescent.png",
  star: "/premium-sky/sprites/star-gold.png",
  rain: "/premium-sky/sprites/rain-drop.png",
  gem: "/premium-sky/sprites/aqua-gem.png",
  kite: "/premium-sky/sprites/letter-kite.png",
  balloon: "/premium-sky/sprites/number-balloon.png",
  heart: "/premium-sky/sprites/heart-balloon.png",
  music: "/premium-sky/sprites/music-notes.png",
  book: "/premium-sky/sprites/story-book.png",
  leaf: "/premium-sky/sprites/leaf-glider.png",
  drum: "/premium-sky/sprites/drum-cloud.png",
  compass: "/premium-sky/sprites/compass-orb.png",
  skyWorld: "/sky-bitmaps/sky-world.webp",
  sunSmile: "/sky-bitmaps/sun-smile.webp",
  cloudFamily: "/sky-bitmaps/cloud-family.webp",
  treasure: "/sky-bitmaps/treasure-instruments.webp",
};

const RAINBOW_SETS = [
  ["Rosa", "Orange", "Gelb", "Grün", "Blau", "Violett"],
  ["Rot", "Gold", "Sonne", "Blatt", "Wasser", "Traum"],
  ["Leise", "Hell", "Warm", "Frisch", "Klar", "Mutig"],
  ["1", "2", "3", "4", "5", "6"],
  ["Do", "Re", "Mi", "Fa", "Sol", "La"],
  ["Atmen", "Schauen", "Wählen", "Legen", "Hören", "Freuen"],
];

const TREASURE_SETS = [
  [
    { id: "kite", label: "Buchstaben", sprite: SKY_SPRITES.kite, answer: true },
    { id: "book", label: "Geschichte", sprite: SKY_SPRITES.book, answer: true },
    { id: "drum", label: "Trommel", sprite: SKY_SPRITES.drum, answer: false },
    { id: "leaf", label: "Blatt", sprite: SKY_SPRITES.leaf, answer: false },
  ],
  [
    { id: "balloon", label: "Zahl", sprite: SKY_SPRITES.balloon, answer: true },
    { id: "gem", label: "Perle", sprite: SKY_SPRITES.gem, answer: true },
    { id: "moon", label: "Mond", sprite: SKY_SPRITES.moon, answer: false },
    { id: "music", label: "Klang", sprite: SKY_SPRITES.music, answer: false },
  ],
  [
    { id: "rain", label: "Regen", sprite: SKY_SPRITES.rain, answer: true },
    { id: "sun", label: "Sonne", sprite: SKY_SPRITES.sun, answer: true },
    { id: "leaf", label: "Natur", sprite: SKY_SPRITES.leaf, answer: true },
    { id: "book", label: "Buch", sprite: SKY_SPRITES.book, answer: false },
  ],
  [
    { id: "heart", label: "Herz", sprite: SKY_SPRITES.heart, answer: true },
    { id: "compass", label: "Mut", sprite: SKY_SPRITES.compass, answer: true },
    { id: "rain", label: "Regen", sprite: SKY_SPRITES.rain, answer: false },
    { id: "balloon", label: "Zahl", sprite: SKY_SPRITES.balloon, answer: false },
  ],
  [
    { id: "music", label: "Melodie", sprite: SKY_SPRITES.music, answer: true },
    { id: "drum", label: "Trommel", sprite: SKY_SPRITES.drum, answer: true },
    { id: "kite", label: "Buchstabe", sprite: SKY_SPRITES.kite, answer: false },
    { id: "gem", label: "Perle", sprite: SKY_SPRITES.gem, answer: false },
  ],
  [
    { id: "star", label: "Stern", sprite: SKY_SPRITES.star, answer: true },
    { id: "rainbow", label: "Bogen", sprite: SKY_SPRITES.rainbow, answer: true },
    { id: "cloud", label: "Wolke", sprite: SKY_SPRITES.cloudA, answer: true },
    { id: "drum", label: "Trommel", sprite: SKY_SPRITES.drum, answer: false },
  ],
];

const RAW_SKY_WONDERLAND_ROUNDS = [
  {
    id: "polar",
    name: "Polarlicht",
    sky: "from-[#14233f] via-[#305d75] to-[#9ad7c4]",
    glow: "#79f2d0",
    accent: "#f8df72",
    constellation: {
      title: "Segelboot",
      order: ["s1", "s2", "s3", "s4", "s5"],
      stars: [
        { id: "s1", x: 19, y: 67, size: 18 },
        { id: "s2", x: 36, y: 42, size: 15 },
        { id: "s3", x: 52, y: 67, size: 18 },
        { id: "s4", x: 36, y: 70, size: 12 },
        { id: "s5", x: 36, y: 22, size: 20 },
        { id: "d1", x: 67, y: 29, size: 12 },
        { id: "d2", x: 77, y: 59, size: 14 },
        { id: "d3", x: 13, y: 30, size: 11 },
      ],
    },
    clouds: [
      { id: "c1", icon: "🌧️", bucket: "Regen", x: 11, y: 19 },
      { id: "c2", icon: "🌤️", bucket: "Sonne", x: 43, y: 11 },
      { id: "c3", icon: "❄️", bucket: "Schnee", x: 69, y: 27 },
      { id: "c4", icon: "🌧️", bucket: "Regen", x: 29, y: 57 },
    ],
    moon: {
      answer: "Halbmond",
      choices: [
        { label: "Vollmond", phase: "full" },
        { label: "Halbmond", phase: "half" },
        { label: "Sichel", phase: "crescent" },
      ],
    },
    comets: [
      { id: "p1", x: 17, y: 72 },
      { id: "p2", x: 29, y: 49 },
      { id: "p3", x: 44, y: 33 },
      { id: "p4", x: 58, y: 45 },
      { id: "p5", x: 72, y: 30 },
      { id: "p6", x: 84, y: 58 },
    ],
  },
  {
    id: "dawn",
    name: "Morgenrot",
    sky: "from-[#71395d] via-[#e68a73] to-[#f8d98d]",
    glow: "#ffd080",
    accent: "#78d7ff",
    constellation: {
      title: "Drachen",
      order: ["s2", "s4", "s5", "s6", "s7"],
      stars: [
        { id: "s1", x: 15, y: 40, size: 12 },
        { id: "s2", x: 27, y: 28, size: 20 },
        { id: "s3", x: 34, y: 68, size: 12 },
        { id: "s4", x: 44, y: 44, size: 17 },
        { id: "s5", x: 58, y: 27, size: 18 },
        { id: "s6", x: 70, y: 48, size: 16 },
        { id: "s7", x: 58, y: 69, size: 18 },
        { id: "d1", x: 82, y: 22, size: 10 },
      ],
    },
    clouds: [
      { id: "c1", icon: "🌤️", bucket: "Sonne", x: 13, y: 23 },
      { id: "c2", icon: "❄️", bucket: "Schnee", x: 39, y: 15 },
      { id: "c3", icon: "🌈", bucket: "Bunt", x: 67, y: 31 },
      { id: "c4", icon: "🌤️", bucket: "Sonne", x: 31, y: 59 },
    ],
    moon: {
      answer: "Sichel",
      choices: [
        { label: "Sichel", phase: "crescent" },
        { label: "Neumond", phase: "new" },
        { label: "Vollmond", phase: "full" },
      ],
    },
    comets: [
      { id: "p1", x: 13, y: 31 },
      { id: "p2", x: 28, y: 45 },
      { id: "p3", x: 42, y: 64 },
      { id: "p4", x: 58, y: 52 },
      { id: "p5", x: 69, y: 34 },
      { id: "p6", x: 85, y: 25 },
    ],
  },
  {
    id: "midnight",
    name: "Mitternacht",
    sky: "from-[#11182e] via-[#333b72] to-[#8667ad]",
    glow: "#c9b6ff",
    accent: "#86f7ff",
    constellation: {
      title: "Krone",
      order: ["s1", "s3", "s5", "s7", "s8"],
      stars: [
        { id: "s1", x: 18, y: 62, size: 18 },
        { id: "s2", x: 25, y: 30, size: 10 },
        { id: "s3", x: 34, y: 38, size: 16 },
        { id: "s4", x: 43, y: 72, size: 11 },
        { id: "s5", x: 51, y: 25, size: 21 },
        { id: "s6", x: 65, y: 39, size: 12 },
        { id: "s7", x: 69, y: 38, size: 16 },
        { id: "s8", x: 83, y: 62, size: 18 },
      ],
    },
    clouds: [
      { id: "c1", icon: "🌈", bucket: "Bunt", x: 14, y: 18 },
      { id: "c2", icon: "🌧️", bucket: "Regen", x: 42, y: 19 },
      { id: "c3", icon: "❄️", bucket: "Schnee", x: 72, y: 32 },
      { id: "c4", icon: "🌈", bucket: "Bunt", x: 32, y: 58 },
    ],
    moon: {
      answer: "Vollmond",
      choices: [
        { label: "Halbmond", phase: "half" },
        { label: "Vollmond", phase: "full" },
        { label: "Neumond", phase: "new" },
      ],
    },
    comets: [
      { id: "p1", x: 14, y: 58 },
      { id: "p2", x: 26, y: 38 },
      { id: "p3", x: 39, y: 27 },
      { id: "p4", x: 54, y: 39 },
      { id: "p5", x: 69, y: 54 },
      { id: "p6", x: 84, y: 41 },
    ],
  },
  {
    id: "raingarden",
    name: "Regenlicht",
    sky: "from-[#51708b] via-[#9fc4dc] to-[#ecf8ff]",
    glow: "#d4f3ff",
    accent: "#38bdf8",
    constellation: {
      title: "Regenschirm",
      order: ["s1", "s2", "s3", "s4", "s5", "s6"],
      stars: [
        { id: "s1", x: 24, y: 58, size: 16 },
        { id: "s2", x: 34, y: 37, size: 14 },
        { id: "s3", x: 48, y: 29, size: 18 },
        { id: "s4", x: 62, y: 37, size: 14 },
        { id: "s5", x: 73, y: 58, size: 16 },
        { id: "s6", x: 49, y: 72, size: 18 },
        { id: "d1", x: 18, y: 28, size: 10 },
        { id: "d2", x: 83, y: 32, size: 12 },
      ],
    },
    clouds: [
      { id: "c1", icon: "🌧️", bucket: "Regen", x: 12, y: 24 },
      { id: "c2", icon: "🌈", bucket: "Bunt", x: 40, y: 14 },
      { id: "c3", icon: "🌧️", bucket: "Regen", x: 68, y: 34 },
      { id: "c4", icon: "🌤️", bucket: "Sonne", x: 29, y: 60 },
    ],
    moon: {
      answer: "Neumond",
      choices: [
        { label: "Neumond", phase: "new" },
        { label: "Halbmond", phase: "half" },
        { label: "Vollmond", phase: "full" },
      ],
    },
    comets: [
      { id: "p1", x: 16, y: 26 },
      { id: "p2", x: 27, y: 42 },
      { id: "p3", x: 40, y: 60 },
      { id: "p4", x: 57, y: 66 },
      { id: "p5", x: 70, y: 51 },
      { id: "p6", x: 84, y: 35 },
    ],
  },
  {
    id: "sunmeadow",
    name: "Sonnenwiese",
    sky: "from-[#81d4ff] via-[#ffe4a3] to-[#b8f4c7]",
    glow: "#ffe58a",
    accent: "#f59e0b",
    constellation: {
      title: "Blume",
      order: ["s1", "s2", "s3", "s4", "s5"],
      stars: [
        { id: "s1", x: 51, y: 28, size: 18 },
        { id: "s2", x: 66, y: 43, size: 16 },
        { id: "s3", x: 51, y: 58, size: 18 },
        { id: "s4", x: 36, y: 43, size: 16 },
        { id: "s5", x: 51, y: 43, size: 21 },
        { id: "d1", x: 19, y: 31, size: 11 },
        { id: "d2", x: 79, y: 65, size: 10 },
      ],
    },
    clouds: [
      { id: "c1", icon: "🌤️", bucket: "Sonne", x: 17, y: 20 },
      { id: "c2", icon: "🌤️", bucket: "Sonne", x: 46, y: 12 },
      { id: "c3", icon: "🌈", bucket: "Bunt", x: 70, y: 34 },
      { id: "c4", icon: "❄️", bucket: "Schnee", x: 31, y: 62 },
    ],
    moon: {
      answer: "Vollmond",
      choices: [
        { label: "Sichel", phase: "crescent" },
        { label: "Vollmond", phase: "full" },
        { label: "Neumond", phase: "new" },
      ],
    },
    comets: [
      { id: "p1", x: 15, y: 66 },
      { id: "p2", x: 30, y: 52 },
      { id: "p3", x: 42, y: 34 },
      { id: "p4", x: 57, y: 28 },
      { id: "p5", x: 72, y: 40 },
      { id: "p6", x: 86, y: 62 },
    ],
  },
  {
    id: "cloudharbor",
    name: "Wolkenhafen",
    sky: "from-[#7dd3fc] via-[#c4e7ff] to-[#fff7cd]",
    glow: "#ffffff",
    accent: "#06b6d4",
    constellation: {
      title: "Leuchtturm",
      order: ["s1", "s2", "s3", "s4", "s5", "s6"],
      stars: [
        { id: "s1", x: 46, y: 72, size: 16 },
        { id: "s2", x: 46, y: 56, size: 14 },
        { id: "s3", x: 46, y: 40, size: 14 },
        { id: "s4", x: 46, y: 24, size: 18 },
        { id: "s5", x: 34, y: 34, size: 13 },
        { id: "s6", x: 58, y: 34, size: 13 },
        { id: "d1", x: 22, y: 58, size: 10 },
        { id: "d2", x: 78, y: 26, size: 12 },
      ],
    },
    clouds: [
      { id: "c1", icon: "🌈", bucket: "Bunt", x: 15, y: 21 },
      { id: "c2", icon: "❄️", bucket: "Schnee", x: 41, y: 17 },
      { id: "c3", icon: "🌤️", bucket: "Sonne", x: 70, y: 29 },
      { id: "c4", icon: "🌧️", bucket: "Regen", x: 29, y: 59 },
    ],
    moon: {
      answer: "Halbmond",
      choices: [
        { label: "Vollmond", phase: "full" },
        { label: "Sichel", phase: "crescent" },
        { label: "Halbmond", phase: "half" },
      ],
    },
    comets: [
      { id: "p1", x: 12, y: 42 },
      { id: "p2", x: 28, y: 30 },
      { id: "p3", x: 42, y: 42 },
      { id: "p4", x: 57, y: 59 },
      { id: "p5", x: 72, y: 47 },
      { id: "p6", x: 86, y: 29 },
    ],
  },
];

export const SKY_WONDERLAND_ROUNDS = RAW_SKY_WONDERLAND_ROUNDS.map((round, index) => ({
  ...round,
  background: SKY_SKYLINE_ASSETS[index % SKY_SKYLINE_ASSETS.length],
  foreground: index % 3 === 0 ? SKY_SPRITES.cloudFamily : index % 3 === 1 ? SKY_SPRITES.rainbow : SKY_SPRITES.treasure,
  rainbow: RAINBOW_SETS[index % RAINBOW_SETS.length],
  treasures: TREASURE_SETS[index % TREASURE_SETS.length],
}));

export const SKY_BUCKETS = [
  { id: "Regen", icon: "💧", color: "bg-sky-100 text-sky-800 border-sky-200" },
  { id: "Sonne", icon: "☀️", color: "bg-amber-100 text-amber-800 border-amber-200" },
  { id: "Schnee", icon: "❄️", color: "bg-cyan-100 text-cyan-800 border-cyan-200" },
  { id: "Bunt", icon: "🌈", color: "bg-rose-100 text-rose-800 border-rose-200" },
];
